name: midterm_app
description: A new Flutter project for the Midterm Exam.
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust based on your current Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5 # Or the latest stable version
  equatable: ^2.0.5     # Required for BLoC Events and the Recipe model

  # Navigation
  go_router: ^14.0.2    # Required for navigating between screens

  # Utilities
  uuid: ^4.4.0          # Required for generating unique Recipe IDs
  intl: ^0.19.0         # Required for date/time formatting (if used, but good practice)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg